### ISSUE TITLE
Move all components to this repository

### ISSUE THREAD

**Issue by autermann** [52North/arctic-sea#1]
## Proposal
Move all Arctic Sea components ([Jan Mayen](https://github.com/52North/janmayen), [Faroe](https://github.com/52North/faroe), [Shetland](https://github.com/52North/shetland), [Svalbard](https://github.com/52North/svalbard), [Iceland](https://github.com/52North/iceland)) to this repository, give them a common prefix for the `groupId` (e.g. `org.n52.arcticsea`) and a common version number (maybe starting at `1.0.0`). Due to dependency convergence we'll currently have to rerelease all components with updated dependencies anyway if e.g. Jan Mayen gets a new release.

## Benefits
* Easier release workflow
* Easier changes across projects
* Easier handling of dependencies
* Easier usage (i.e. common versioning scheme)

## Todo
* [ ] Migrate all open issues from  [Jan Mayen](https://github.com/52North/janmayen)
* [ ] Migrate all open issues from [Faroe](https://github.com/52North/faroe)
* [ ] Migrate all open issues from  [Shetland](https://github.com/52North/shetland)
* [ ] Migrate all open issues from  [Svalbard](https://github.com/52North/svalbard)
* [ ] Migrate all open issues from [Iceland](https://github.com/52North/iceland)
* [ ] Move source code of [Jan Mayen](https://github.com/52North/janmayen) in subdirectory called `janmayen`
* [ ] Move source code of [Faroe](https://github.com/52North/faroe) in subdirectory called `faroe`
* [ ] Move source code of [Shetland](https://github.com/52North/shetland) in subdirectory called `shetland`
* [ ] Move source code of [Svalbard](https://github.com/52North/svalbard) in subdirectory called `svalbard`
* [ ] Move source code of [Iceland](https://github.com/52North/iceland) in subdirectory called `iceland`
* [ ] Create a parent `pom.xml` using the component's `pom.xml`
```xml
<groupId>org.n52.arcticsea</groupId>
<artifactId>arctic-sea</artifactId>
<version>1.0.0-SNAPSHOT</version>
```
* [ ] Update the component's `pom.xml` to use the new parent, change the `groupId` to `org.n52.arcticsea.$component`, e.g.:
```xml
<groupId>org.n52.arcticsea.iceland</groupId>
<artifactId>iceland</artifactId>
<version>1.0.0-SNAPSHOT</version>
```
```xml
<groupId>org.n52.arcticsea.faroe</groupId>
<artifactId>faroe-annotations</artifactId>
<version>1.0.0-SNAPSHOT</version>
```

* [ ] Create the initial release
* [ ] Update depending components (SOS, WPS, Importer, ...)
* [ ] Clear [Jan Mayen](https://github.com/52North/janmayen) and create a simple README referencing this repository
* [ ] Clear [Faroe](https://github.com/52North/faroe) and create a simple README referencing this repository
* [ ] Clear [Shetland](https://github.com/52North/shetland)  and create a simple README referencing this repository
* [ ] Clear [Svalbard](https://github.com/52North/svalbard) and create a simple README referencing this repository
* [ ] Clear  [Iceland](https://github.com/52North/iceland) and create a simple README referencing this repository
* [ ] Make sure Travis CI is working

## Questions/To Discuss/To Check
* [ ] What versioning scheme to use? Start at `1.0.0`?
* [ ] Use `org.n52.arcticsea` as `groupId` for all modules?
* [ ] Are there any feature branches that are not yet merged?

**Comment by ridoo** [comment]
I think we should start with version 52. We should do this for all software we'll release at 52North ;).

To be serious: I am fine with 1.0.0

**Comment by ridoo** [comment]
Want about the package names? I'd say, they should stay the same, shouldn't they? I mean, moving all under `arcticsea` would require all dependent coffee to recompile

**Comment by EHJ-52n** [comment]
* **Versioning**: I would like starting at 1.0.0
* **GroupId**:  I would like to have all under the same groupId `arctic-sea` because all these modules are part of *the arctic sea*.
* **Open branches**:  [/EHJ-52n/svalbard/tree/feature/coding-required-for-data-import](/EHJ-52n/svalbard/tree/feature/coding-required-for-data-import)

**Comment by autermann** [comment]
> GroupId: I would like to have all under the same groupId arctic-sea because all these modules are part of the arctic sea.

I don't think the `groupId` can contain hyphens...

> Open branches: /EHJ-52n/svalbard/tree/feature/coding-required-for-data-import

Is there already a PR for that?

**Comment by EHJ-52n** [comment]
>> Open branches: /EHJ-52n/svalbard/tree/feature/coding-required-for-data-import
>
> Is there already a PR for that?

created one just now: 52North/svalbard#8

>> **GroupId**: I would like to have all under the same groupId `arctic-sea` because all these modules are part of *the arctic sea*.
> 
> I don't think the groupId can contain hyphens...

`arcticsea` is okay for me, too.

Specifications: [Apache Maven](https://maven.apache.org/guides/mini/guide-naming-conventions.html) &rarr; [Java Naming Specification](https://docs.oracle.com/javase/specs/jls/se6/html/packages.html#7.7]

**Comment by autermann** [comment]
Okay, as I have no idea how to sell the a _newer_ `1.0.0` release to Ann, I'll propose to go with `3.0.0`, as Iceland with the highest version number is at `2.0.0`...

**Comment by CarstenHollmann** [comment]
I agree with you to go on with `3.0.0`  and a common prefix for all.
